export interface Empleado {
    id:number,
    nombres:string,
    apellidos:string,
    genero:string,
    estadoCivil:string,
    fechaNacimiento:string,
    edad:number,
    dpi:string,
    nit:string,
    afiliacionIGSS:string,
    afiliacionIRTRA:string,
    pasaporte:string,
    direccion:string,
    salarioBase:number,
    bonificaciones:number,
    descuentos:number,
}
